# Generated by Django 5.2.8 on 2026-02-06 00:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0022_participant_bmi_participant_willing_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DomesticRelatedChallenge18Response',
            new_name='DomesticRelatedChallenge17Response',
        ),
        migrations.RenameModel(
            old_name='WorkRelatedChallenge11Response',
            new_name='DomesticRelatedChallenge20Response',
        ),
        migrations.RenameModel(
            old_name='WorkRelatedChallenge8Response',
            new_name='LeisureRelatedChallenge22Response',
        ),
        migrations.RenameModel(
            old_name='LeisureRelatedChallenge26Response',
            new_name='LeisureRelatedChallenge27Response',
        ),
        migrations.RenameModel(
            old_name='LeisureRelatedChallenge23Response',
            new_name='TransportRelatedChallenge12Response',
        ),
        migrations.RenameModel(
            old_name='TransportRelatedChallenge16Response',
            new_name='TransportRelatedChallenge15Response',
        ),
        migrations.RenameModel(
            old_name='DomesticRelatedChallenge21Response',
            new_name='WorkRelatedChallenge10Response',
        ),
        migrations.RenameModel(
            old_name='TransportRelatedChallenge13Response',
            new_name='WorkRelatedChallenge7Response',
        ),
    ]
