# Generated by Django 5.2.8 on 2026-03-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpas', '0023_rename_domesticrelatedchallenge18response_domesticrelatedchallenge17response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='wave1_missing_code_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='wave1_monitor_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='wave1_survey_return_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
