# Generated by Django 5.1.3 on 2026-03-06 04:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testpas", "0025_leisurerelatedchallenge29response_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LeisureRelatedChallenge29Response",
            new_name="MindfulnessRelatedChallenge29Response",
        ),
        migrations.RenameModel(
            old_name="LeisureRelatedChallenge32Response",
            new_name="MindfulnessRelatedChallenge32Response",
        ),
    ]
