# Generated by Django 5.1.3 on 2026-04-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "testpas",
            "0026_rename_leisurerelatedchallenge29response_mindfulnessrelatedchallenge29response_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="registration_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
