# Generated by Django 5.1.3 on 2026-04-30 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testpas", "0027_participant_registration_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge1Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("q1", models.PositiveSmallIntegerField()),
                ("q2", models.PositiveSmallIntegerField()),
                ("q3", models.PositiveSmallIntegerField()),
                ("q4", models.PositiveSmallIntegerField()),
                ("q5", models.PositiveSmallIntegerField()),
                ("q6", models.PositiveSmallIntegerField()),
                ("q7", models.PositiveSmallIntegerField()),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge1_responses",
                        to="testpas.participant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge1_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
