"""
Django settings for testPAS project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

import environ
from dotenv import load_dotenv
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

import dj_database_url
import os

# Database configuration
# Switch between local (SQLite) and production (Render PostgreSQL)
# Option 1: Set USE_LOCAL_DB=True in .env file for local testing
# Option 2: Set DATABASE_URL environment variable for production (Render automatically sets this)
# Option 3: If neither is set, defaults to local SQLite for safety

USE_LOCAL_DB = os.environ.get('USE_LOCAL_DB', 'False').lower() == 'true'
DATABASE_URL = os.environ.get('DATABASE_URL')
# Use DATABASE_URL if provided (Render PostgreSQL), else default to SQLite
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'cm_intervention',  
#         'USER': 'cm_intervention_user',  
#         'PASSWORD': 'J4g5pu8Tvd8zo9tL3qIrS6W9lfhvAFNg',  
#         'HOST': 'dpg-d46kcdmuk2gs73882790-a.ohio-postgres.render.com', 
#         'PORT': '5432',
#     }
# }

# Detect if we're running on Render
IS_RENDER = os.environ.get('RENDER') == 'true' or 'render.com' in os.environ.get('HOSTNAME', '')

if DATABASE_URL and not USE_LOCAL_DB:
    # Production: Use PostgreSQL from Render
    db_config = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=0,      # OK: no long-lived conns
        ssl_require=True,    # <-- sets sslmode=require
    )

    db_config.setdefault("OPTIONS", {})
    db_config["OPTIONS"].update({
        "connect_timeout": 10,
        "keepalives": 1,
        "keepalives_idle": 30,
        "keepalives_interval": 10,
        "keepalives_count": 5,
    })

    DATABASES = {"default": db_config}
else:
    # Local development: Use SQLite
    # WARNING: If running on Render and DATABASE_URL is not set, this will use SQLite
    # which won't have the production database tables. Make sure DATABASE_URL is set
    # in Render dashboard for all services (web, worker, beat).
    if os.environ.get('RENDER'):
        import warnings
        warnings.warn(
            "Running on Render but DATABASE_URL is not set! "
            "The Celery worker/beat services need DATABASE_URL in their environment variables. "
            "Go to Render dashboard > Your Service > Environment > Add DATABASE_URL",
            UserWarning
        )
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
env = environ.Env()
environ.Env.read_env(
    env_file=os.path.join(BASE_DIR, ".env")
)
SECRET_KEY = os.environ.get('SECRET_KEY')
DEBUG = True   # Set to True for development, False for production
if not SECRET_KEY:
    raise ValueError("The SECRET_KEY setting must not be empty.")


# TEST_MODE = False  # Set to True for 112-minute testing mode
# Set BASE_URL with Render-aware defaults
BASE_URL = os.getenv('BASE_URL')
if not BASE_URL:
    # Try to detect Render URL from environment
    if IS_RENDER:
        # Default Render URL format - user should set BASE_URL explicitly
        import warnings
        warnings.warn(
            "BASE_URL not set on Render! Please set BASE_URL environment variable in Render dashboard. "
            "Using fallback: https://testpas-web.onrender.com",
            UserWarning
        )
        # BASE_URL = 'https://testpas-web.onrender.com'
        BASE_URL = 'https://confidentmoves.onrender.com'
    else:
        # Local development default
        BASE_URL = 'http://127.0.0.1:8000'

LOGIN_URL = '/login/'  # Default login URL for the application

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = os.path.dirname(os.path.abspath(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')

ALLOWED_HOSTS = ['*']
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases



# # # SendGrid configuration
# SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',  
    'testpas',
    'django_celery_beat',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# ROOT_URLCONF = "testpas.urls"
ROOT_URLCONF = 'config.urls'
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

#Time settings
USE_TZ = True
TIME_ZONE = 'America/Chicago'
# Celery settings

# Testing Configuration
# Enable test mode via env var: TEST_MODE=true|1|yes
TEST_MODE = str(os.getenv('TEST_MODE', 'false')).lower() in ('1', 'true', 'yes')
TIME_COMPRESSION = True
SECONDS_PER_DAY = 30 # Use 86400 for real-world days. 30 seconds = 2 checks per day with 15-second Celery Beat interval
# TEST_TIME_SCALE = 10  # 1 day = 10 seconds for testing
# TEST_TIME_SCALE = float(os.getenv('TEST_TIME_SCALE', '5'))  # 1 day = 1 second (or set to 60 for minutes)
# CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_TASK_TRACK_STARTED = True
# # CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Chicago'
CELERY_ENABLE_UTC = False
# Prevent duplicate task execution
CELERY_TASK_ACKS_LATE = True  # Acknowledge tasks AFTER completion, not before
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Reject tasks if worker dies
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Only prefetch one task at a time to prevent duplicates
CELERY_TASK_MAX_RETRIES = 0  # Don't automatically retry failed tasks (we handle retries manually)
CELERY_TASK_DEFAULT_RETRY_DELAY = 0  # No default retry delay
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'run-timeline-checks': {
        'task': 'testpas.tasks.run_daily_timeline_checks',
        'schedule': 15.0 if TIME_COMPRESSION else 86400.0,
    },
}
# from celery import Celery
# import ssl
# ssl_context = ssl.create_default_context()
 
# app = Celery("config")
# app.conf.broker_transport_options = {
#     "ssl": ssl_context
# }
 
# CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL")
# Celery broker URL - can be overridden by REDIS_URL or CELERY_BROKER_URL env vars in celery.py
# Render typically provides REDIS_URL, which will be used by celery.py
CELERY_BROKER_URL = os.environ.get("REDIS_URL") or os.environ.get("CELERY_BROKER_URL") or "redis://localhost:6379/0"
# CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND")
CELERY_RESULT_BACKEND = None
CELERY_TASK_IGNORE_RESULT = True
# Define how many seconds represent one simulated "day"

# Email settings
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False  
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = 'The Confident Moves Research Team <vuleson59@gmail.com>'
# DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER') ## Change to your email address when run
# # WSGI_APPLICATION = "testpas.wsgi.application"
WSGI_APPLICATION = "config.wsgi.application"


ATOMIC_REQUESTS = True




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'assets'),
]
STATIC_ROOT = BASE_DIR / "staticfiles"

SESSION_COOKIE_AGE = 86400  # 1 day in seconds
# Make sure the session expires when the user closes the browser
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

STORAGES = {
    # Enable WhiteNoise's GZip and Brotli compression of static assets:
    # https://whitenoise.readthedocs.io/en/latest/django.html#add-compression-and-caching-support
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# STATIC_URL = "static/"
# # The `STATIC_ROOT` setting in Django is used to specify the directory where Django will collect all
# # static files from various applications into one location when you run the `collectstatic` management
# # command. This directory is typically used for serving static files in production.
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'staticfiles'),
# ]

# # Whitenoise settings to handle static files in production
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

WHITENOISE_KEEP_ONLY_HASHED_FILES = True
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
